const locale = {
    nick: '昵称',
    nickError: '昵称不能少于3个字符',
    mail: '邮箱',
    mailError: '请填写正确的邮件地址',
    link: '博客',
    placeholder: '随便说点什么喵～o(=•ェ•=)m \n没有登录也是完全没问题的哦～',
    sofa: '快来发评论吧~',
    submit: '提交',
    reply: '回复',
    cancelReply: '取消回复',
    comment: '评论',
    more: '加载更多...',
    preview: '预览',
    emoji: '表情',
    uploadImage: '上传图片',
    seconds: '秒前',
    minutes: '分钟前',
    hours: '小时前',
    days: '天前',
    now: '刚刚',
    uploading: '正在上传',
    login: '登录',
    logout: '退出',
    admin: '博主',
    word: '字',
    wordHint: '评论字数应在 $0 到 $1 字之间！\n当前字数：$2',
};
